name: Bug Report
description: Report a problem with rustaceanvim
labels: [bug]
body:

  - type: markdown
    attributes:
      value: |
        _Before reporting:_ search [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
        See also: [Troubleshooting section of README.md](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#minimal-config).

  - type: input
    attributes:
      label: "Neovim version (nvim -v)"
      placeholder: "v0.9.0"
    validations:
      required: true
  - type: input
    attributes:
      label: "Operating system/version"
      placeholder: "NixOS 22.05"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Output of :checkhealth rustaceanvim"
      render: "console"
      placeholder: |
        Please paste the output here, as it may contain important information for debugging.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "How to reproduce the issue"
      description: |
        Steps to reproduce using a [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).
      placeholder: |
        mkdir -p /tmp/minimal
        NVIM_DATA_MINIMAL=/tmp/minimal NVIM_APP_NAME="nvim-minimal" -u minimal.lua
        :edit foo.rs
        4j
        :RustHoverActions
      render: "console"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behaviour"
      description: "Describe the behaviour you expect. May include logs, images, or videos."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Actual behaviour"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "The minimal config used to reproduce this issue."
      description: |
        See [this example](https://github.com/mrcjkb/rustaceanvim/blob/master/tests/minimal.lua).
      placeholder: |
        -- Paste your minimal config here. Please base it on the example provided by this plugin,
        -- including any additional plugins that must be installed for the issue to be reproducible.
      render: "Lua"
    validations:
      required: true
